### ISSUE TITLE
Is `partition_asymmetry` with `Uylings` variant usable?

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#1000]
I find peculiar the implementation of the **Uylings variant** of for the partition asymmetry:

https://github.com/BlueBrain/NeuroM/blob/127d6fd45167b3cf2ae6d41c51ad241846d082dc/neurom/features/bifurcation.py#L102-L124

because all bifurcation points the children of which are leaves will have downstream counts `n,m = (1, 1)`, therefore all morphs would fail the check.

Am I missing a use case where this could work?

@mgeplf @lidakanari @arnaudon @adrien-berchet

**Comment by adrien-berchet** [comment]
I don't know this feature but it looks weird indeed. The exception message suggests that the condition should be `if n + m < c`, isn't it?

Also, I realize that the neurite feature should not just iterate over the bifurcation points to compute this because the bifurcation point feature iterates over the complete subtree of this point. Instead it is possible to iterate just once over the all the bifurcation points to compute the sizes of children subtrees and then the partition values (using a reverse breadth-first traversal). But the current implementation iterates many times over the subtrees (basically we could have a O(1) complexity instead of O(2)).

**Comment by eleftherioszisis** [comment]
The problem with `n + m < c` is that there would be a division with zero for the leaf bifurcations.

As this question is not about optimization, we shouldn't drag that in here. My first concern is about the features being correct. Optimization can come later if needed.

**Comment by adrien-berchet** [comment]
Ah yes sorry. Well, you will have to read the related articles then :innocent: 

And yes the optimization will come later, I just saw that when I read the code.

**Comment by eleftherioszisis** [comment]
The linked paper states:
``` By definition Ap(1, 1) = 0.``` (bottom of page 398)
where:
```
Ap(r, s) = |r - s| / (r + s - 2)
```
