### ISSUE TITLE
Sholl diagram needed

### ISSUE THREAD

**Issue by a1eko** [BlueBrain/NeuroM#180]
For compatibility with experimental data, a Sholl diagram is needed. Something like this:

```
    radial_distances = [array of distances from 0 to max radial distance]
    intersections = nrn.get_intersections(radial_distances, neurite_type=ttype)
    plt.plot(radial_distances, intersections)
```

**Comment by juanchopanza** [comment]
@lidakanari @eleftherioszisis Any comments on this? I believe the possibility of implementing this has been discussed recently.

**Comment by lidakanari** [comment]
Yes, indeed. This have been discussed as a possible implementation in the future. However, the code is a bit more complicated than the one described by Alexander. Here is the corresponding paper: http://www.sciencedirect.com/science/article/pii/S0165027014000272

First of all, I would propose that we concentrate on the extraction of the data in the Sholl analysis function and we leave the plotting to the user (that will indeed be trivial).  

Second, since Sholl analysis require the parsing of the tree for each circle in order to define the number of intersections, I would proposed an optimized approach: first define all the circles and then parse the tree once, calculating all intersections for all circles.

**Comment by a1eko** [comment]
*"...an optimized approach: first define all the circles and then parse the tree once, calculating all intersections for all circles."*
Yes, it will be linear in the number of points, *n*. I suppose same algorithm is used for touch detections as well! If not, it could be as slow as *n^2*.

**Comment by mgeplf** [comment]
Hello @a1eko,

I have added this feature in #570, and would appreciate it if you gave it a shot, and see if it works for your use case.

Thanks.

**Comment by mgeplf** [comment]
#570 merged
