### ISSUE TITLE
Provide uniform morphology check behaviour

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#187]
The morphology checkers in `neurom.check.morphology` artibrarily return `True`, `False` or collections of information. For validation tools, it would be useful to have a simple pass/fail interface for each checker and for an ensemble of checkers.

**Comment by lidakanari** [comment]
That could be tricky. Sometimes contradictory tests should be True in order to define the morphology as good. For example the check "Does it has apical?" should be True if the cell is a PC, but False in the cell is IN. Is there a nice way to generalize this concept, because apparently we cannot assume that the cell will be a PC or an IN a priori.

**Comment by juanchopanza** [comment]
I think the point here is to make sure tests return False when they fail, and True when they pass. That's all. How you determine pass or fail conditions is a separate issue.

**Comment by lidakanari** [comment]
Ah, ok. If this is independent of the 'pass/fail' definition it makes sense to return a True/False statement.
