### ISSUE TITLE
Getting test failures with matplotlib 1.5.1

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/NeuroM#221]
Seems 'add_collection3d' is no longer available on 'AxesSubplot':

```
======================================================================
ERROR: test_view.test_neuron3d
----------------------------------------------------------------------
Traceback (most recent call last):
  File "*******************/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/*****/src/NeuroM-bbp/neurom/view/tests/test_view.py", line 108, in test_neuron3d
    fig, ax = view.neuron3d(neuron0)
  File "/home/*****/src/NeuroM-bbp/neurom/view/view.py", line 592, in neuron3d
    tree3d(temp_tree, **kwargs)
  File "/home/*****/src/NeuroM-bbp/neurom/view/view.py", line 448, in tree3d
    ax.add_collection3d(collection)
AttributeError: 'AxesSubplot' object has no attribute 'add_collection3d'

----------------------------------------------------------------------
```

matplotlib version:

```
$ python -c 'import matplotlib; print matplotlib.__version__' 
1.5.1
```

**Comment by eleftherioszisis** [comment]
Is this happening in your local machine? 

I cannot reproduce it in mine, but it did occur in the jupyter notebook app in the collaboratory
 with:
```python
%matplotlib inline
```
 I still haven't figured out what exactly is causing it but it appears that it has to do with the

```python
from mpl_toolkits.mplot3d import Axes3d
```
and
```python
ax = f.add_subplot(111, projection='3d')
```
in combination with the 
```plt.gcf ```
which returns the current figure in which all the neurites are plotted. These axes objects must become Axes3DSubplot objects but instead it becomes an AxesSubplot which does not have the add_collection3d method. My suspicion on gcf is correlated with the fact that this error is not apparent if tree3d is used on a single neurite, where the figure is used once. :/

In order to fix the problem with the ipython notebook I used the magic
```python
%matplotlib notebook
```
instead of inline

**Comment by mgeplf** [comment]
I'm only running the tests, not using anything else.

Which version of matplotlib are you using?

**Comment by lidakanari** [comment]
Yes, this is an issue that I had in the past. After a lot of search I found that it has been generally attributed to a bug in specific matplotlib versions that do not seem to work with all the platforms. 

The default we use is:
 matplotlib (1.3.1)

If you manage to find out what is wrong with this issue, it would be very helpful, but I couldn't find a way to overcome this issue, I just installed a different matplotlib version.
