### ISSUE TITLE
Axes scaling when plotting morphology

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/NeuroM#279]
Based on feedback from @jdcourcol on the NeuroM figure generated here:
https://github.com/BlueBrain/BluePyOpt/blob/master/examples/l5pc/L5PC.ipynb
we were wondering if it wouldn't make more sense if NeuroM would keep the aspect ratio when plotting morphologies. The morphology looks a bit unnatural with the current default plotting.
(maybe this could be an option ?)

**Comment by lidakanari** [comment]
Could you please define "keep the aspect ratio"? Do you need this to be X-range/Y-range in morphology to be equal to the range of the axes on the plot? 

Currently, you can define this ratio by choosing the xlim - ylim. However, we could change the default values in order to be consistent with what is expected. Due to lack of specs for this the decision for the axes ratio was arbitrary, so I wouldn't mind making it consistent with a spec if that is well defined :)

**Comment by jdcourcol** [comment]
We would like to have the scale to be the same in both axes. So that the shape of the neuron is not transformed. The resulting image does not need to be a square.

**Comment by wvangeit** [comment]
And regarding 'specs'. Don't think we need this for this function, would rather make default what most people are expecting. Personally I think that most people would want to see a morphology in the same shape has if looking at a slice, but of course I'm not sure. That's why I was suggesting you could add it as an option (one way or the other).

**Comment by lidakanari** [comment]
I agree with you Werner. There is no standard. So in the lack of a standard I just left the figure's axes to be defined a bit arbitrary. The option to choose them is to define xlim and ylim. So if you need something specific select the appropriate xlim, ylim. 
In order to define a standard, I would like a intuition of what would be better:  do we need to have xlim == ylim? That will make the plot square. Do we prefer to have the cell as it would look in a slice (that is usually not square), so xlim=horizontal range of cell, ylim= vertical range of cell.

**Comment by wvangeit** [comment]
There is no standard, and I really don't think we need one either: https://xkcd.com/927/
The only thing we're proposing is that the most used case is probably that 'it would look like in a slice', so it could be the default. Maybe it shouldn't, we don't know for sure, it's ok to close the ticket. 
People can change the xlim, ylim every time they plot a morphology, but an option (e.g. keep_aspect_ratio, stretch etc ?) would be much more handy.

**Comment by jdcourcol** [comment]
thank you Lida. I will give it a try as soon as a package is available.
