### ISSUE TITLE
Difference between h5 file asc file and pneumatk

### ISSUE THREAD

**Issue by orena1** [BlueBrain/NeuroM#322]
I was using pneumatk in the past, and now I am trying to transition to NeuroM, but it seems that there is a small difference between the results of pneumatk and NeuroM. Also there is a very big difference between NeuroM h5 file and asc file, I think those files should be identical:

```python

from neurom import ezy
from neurom.features import NEURITEFEATURES, NEURONFEATURES
from neurom.core.types import TreeType


H5pop = [ezy.load_neuron(cell) for cell in ['C050600B1.h5']]
H5neurom = [] 
H5neurom.append([round(sum(NEURITEFEATURES['section_lengths'](i, neurite_type=TreeType.basal_dendrite)),2) for i in H5pop])
H5neurom.append([round(sum(NEURITEFEATURES['section_volumes'](i, neurite_type=TreeType.basal_dendrite)),2) for i in H5pop])
H5neurom.append([round(sum(NEURITEFEATURES['section_areas'](i, neurite_type=TreeType.basal_dendrite)),2) for i in H5pop])

import pneumatk as pn
popPne = [ pn.io.load(cell) for cell in ['C050600B1.h5']]
H5pnue =[]
H5pnue.append([sum(i.get_section_lengths(neurite_type='basal')) for i in popPne])
H5pnue.append([sum(i.get_section_volumes(neurite_type='basal')) for i in popPne])
H5pnue.append([sum(i.get_section_surface_areas(neurite_type='basal')) for i in popPne])

ASCpop = [ezy.load_neuron(cell) for cell in ['C050600B1.asc']]
ASCneurom =[]
ASCneurom.append([sum(NEURITEFEATURES['section_lengths'](i, neurite_type=TreeType.basal_dendrite)) for i in ASCpop])
ASCneurom.append([sum(NEURITEFEATURES['section_volumes'](i, neurite_type=TreeType.basal_dendrite)) for i in ASCpop])
ASCneurom.append([sum(NEURITEFEATURES['section_areas'](i, neurite_type=TreeType.basal_dendrite)) for i in ASCpop])


import pandas as pnd
pnd.DataFrame([H5pnue, H5neurom, ASCneurom],index = ['h5 pneumatk', 'h5 neurom', 'asc neurom'], columns = ['Basal length' , 'Basal volume', 'Basal area'] )

```

The code result in this output
```
                Basal length     Basal volume       Basal area
h5 pneumatk  [3155.24807618]  [1336.19777075]  [6218.93758029]
h5 neurom          [3109.97]        [1345.05]        [6703.85]
asc neurom   [3109.96568975]  [5380.19536895]  [13624.3941565]
```
The mrphologies are in this file
[Morphs.zip](https://github.com/BlueBrain/NeuroM/files/247541/Morphs.zip)
The morphologies were taken from 
l2/2012.07.23/morphologies/ascii
and 
l2/2012.07.23/morphologies/h5

What do you think?
Thanks.

**Comment by lidakanari** [comment]
Hi Oren,

First of all, thank you for the analysis! It is very useful for debugging indeed :)

There are some errors in the pneumatk calculations, so I expect the differences between pneumatk and NeuroM. However the differences between asc and h5 format should not be present. I also noticed a problem recently (I assume this has to do with the ascii loader) with the diameters of ascii files. I have to check this further to make sure that I know what is going wrong there. 

Another issue is that we are not 100% sure that the initial converter is OK. As a result, the two files might not be identical. 

Lida

**Comment by juanchopanza** [comment]
Hi Oren,

I can't speak for `pneumatk`, but I know that `NeuroM` is quite well tested for `h5` and `swc`. The `NL ascii` reader is experimental because we have no data we can fully trust, because the format has no specification. However, why do you expect the `.asc` file to be equivalent to the `h5` one? Do you have a tool that you fully trust to make the conversion between one and the other?

**Comment by juanchopanza** [comment]
@lidakanari @orena1 It would also be interesting to see the `.asc` numbers with `pneumatk`, for completeness! Also, do either of you know if NL stores radii or diameters?

**Comment by lidakanari** [comment]
@juanchopanza From the data Oren just shared it should be the same as h5 (so diameter). If you check the two files, they contain exactly the same values. 

Could we at least check that the diameters are loaded correctly, because I suspect that the factor of 2x in the area (between asc and h5) is caused from the inconsistency of radii - diameters.

**Comment by juanchopanza** [comment]
@lidakanari It is quite likely that there is a radius/diameter problem. The relevant reader code [is here](https://github.com/BlueBrain/NeuroM/blob/master/neurom/io/neurolucida.py#L156), and it seems to assume the 4th component is a radius.

**Comment by orena1** [comment]
@juanchopanza I did not managed to open the asc files with `pneumatk`

**Comment by juanchopanza** [comment]
With #323, the neurite volume and area numbers are compatible. Some small differences remain, which might require some detailed investigation of the data itself, or the production of `h5` and `neurolucida` samples that we can be completely sure are equivalent. These are the numbers I get after the fix:

```python
h5 total neurite surface area: 22321.4425649
nl total neurite surface area: 22186.5760705
h5 total neurite volume: 2533.15174575
nl total neurite volume: 2423.22948318
```

**Comment by lidakanari** [comment]
Thanks Juan! That looks much better :+1:

**Comment by juanchopanza** [comment]
I will re-open until we understand the remaining differences.

**Comment by juanchopanza** [comment]
FYI I opened #324, specifically about the h5/NL issue in `neurom`.

**Comment by juanchopanza** [comment]
FYI I opened #324, specifically about the h5/NL issue in `neurom`.

**Comment by juanchopanza** [comment]
Note that both the `h5` and `.asc` files used in this comparison break some valid assumptions that can be made of the data and are used in `NeuroM`:

*  The `h5` does not have real duplicate points on neurite section-section boundaries. It duplicates (x, y, z), but not necessarily d. The assumption is that duplicate points have equal (x, y, z, d). This is now formally specified in the [hbp h5 spec](https://developer.humanbrainproject.eu/docs/projects/morphology-documentation/0.0.2/h5v1.html#file-format)
* The `.asc` file adds similar "duplicate" points at neurite section-section boundaries. These do not appear on "standard" `.asc` files, and seem to be an artifact of some kind of "repair" process or otherwise performed by a "MUK". This breaks the assumption that there are no duplicated points in section-section boundaries. Note that this mangling process is also BBP-specific and ill-defined.

For these reasons, I am reverting the duplicate removal recently introduced for NL `.asc` files. See PR #360. If and when the "duplicate" insertion process is formalized, we may consider making `NeuroM` aware of it.
