### ISSUE TITLE
Partition function output doesn't seem to agree with other section measurements

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#330]
I am trying to compute the dependence between functions and I noticed that the partition function doesn't seem to be computed for all the sections:

```python
from neurom.features import get
from neurom import ezy

n = ezy.load_neuron('./test_data/swc/Neuron.swc')

get('number_of_sections', n)
# Out[10]: array([ 84.])

sl = get('section_lengths', n)
len(sl)
# Out[14]: 84

sp = get('partition', n)
len(sp)
# Out[16]: 40

```

Notice that the length of the array is not equal to the number of sections, as expected. 
I'm not sure where the error is but could someone look into this?

**Comment by eleftherioszisis** [comment]
I basically asked Leda to open this issue because she has the newest version of NeuroM. I have a previous one and spotted this problem when calculating the branch orders. 

This issue was not present two weeks ago where I was using the same functionality to calculate the section length per branch order. How come this passes through the tests?

**Comment by eleftherioszisis** [comment]
OK, after checking a little into the features, I think that there is no error after all and that the partition values are indeed 40. I took into account a different branch order convention, thus I assumed that they should be less. No wonder why the tests do not fail xD
