### ISSUE TITLE
Change in behaviour of neuron checking functions

### ISSUE THREAD

**Issue by juanchopanza** [BlueBrain/NeuroM#429]
The neuron checking functions were designed at a time when NeuroM was an SWC-only package. As such, it made sense to return IDs of points that caused failures. This was intended to help determined users to debug SWC morphology files. However, NeuroM now deals with HDF5 and (experimentally) with NeuriLucida .asc files, for which the concept of point ID is meaningless. 

I suggest changing the reporting of failures to either return nothing, or return a section ID, point ID pair. The latter can be used to debug interactively and programatically (but should not be persisted.)

Does this make sense? And if so, do we return nothing, or the ID pair?

**Comment by lidakanari** [comment]
It makes sense to change this. However, we have the following issue. It is easy to find a section - segment in h5, but for swc and NLascii that would be impossible. The segment ID is easier for both NLascii and swc because you can search for this line. Similarly, in h5 you can search for a line (segment ID) in the list of points, provided that you start counting from 1. I am not sure if it makes sense to return anything at all, given the inconsistencies between files, but we must check what could be useful for debugging? Possibly return the point as (x, y, z, d)?

**Comment by juanchopanza** [comment]
This isn't for searching in files, for the reasons you mentioned (and I tried to explain in the original post but wasn't clear enough.) Returning the IDs could allow to debug in the same program that reads in the file. So one would get the point from a neuron object. If is not for searching in files. I don't think we can reliably support debugging the files separately.

As for returning a point, these contain floating point and I don't think it is safe to use them to identify points in a file.

**Comment by lidakanari** [comment]
OK, then it definitely makes sense to use the internal representation's data then (SecID, SegID seems reasonable). I doubt that anything can be done internally to "fix" the problem given that it is not possible to change the structure or save it. However, it might be useful to track the issue within the file that contains the information.

**Comment by juanchopanza** [comment]
Yes, the benefits of this are quite limited, but I think the information might be useful for expert debugging.
