### ISSUE TITLE
morph_stats should support a large number of morphologies

### ISSUE THREAD

**Issue by jdcourcol** [BlueBrain/NeuroM#538]
Currently, using a lot of morphologies (> 10000) uses a lot of memory and that makes morph_stats to hang for ever.
The reason being that all the statistics are being kept in memory and then written into a report (json or csv).

**Comment by mgeplf** [comment]
I can probably fix this for the CSV version, but I would have to look at the best way to incrementally write json files.

**Comment by juanchopanza** [comment]
Careful with the `--as-population` option. Also, is it due to the stats being kept in memory, or the morphologies (Neurn objects), or both?

**Comment by jdcourcol** [comment]
@juanchopanza : It is true that I cannot assert that the memory was consumed by the statistics and not the morphologies.
 
> Careful with the --as-population option.
Can you elaborate on that ?

**Comment by juanchopanza** [comment]
It collects summary stats for a whole population, not individual morpholigies. So you need to be clever about how that is done w/o keeping the statistics in memory.

**Comment by mgeplf** [comment]
I would probably do that separately, but it's possible to do online aggregation instead of in batch, I think.  I will look at the code.

**Comment by asanin-epfl** [comment]
Would need a total refactoring of `morph_stats`. With the current design it is impossible to patch.

**Comment by arnaudon** [comment]
One can do it in batch upon calling the extract_dataframe method I think, instead of bruteforcing many morphs into it. It will in any case take for ever to compute many stats on such a large number of morphologies. For such usecase, I would use a distributed parallel computation calling only the neurom.get functions one is interested in. This morphs_stat is designed to be use on a a reasonable number of morphologies.
