### ISSUE TITLE
Refactor viewing code

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/NeuroM#607]
- [x] Remove AGG backend
- [x] Make sure plotting doesn't repeatedly save the figure
- [x] Make sure develop API gives more control over styling
- [ ] update examples
- [x] Update doc
- [x] test w/ old matplotlib versions
- [ ] measure performance

**Comment by mgeplf** [comment]
Currently the dependency tree is:
`neurom.viewer` depends on `view.(neuron, tree, soma neuron3d, tree3d, soma3d)`,
and `view.neuron` depends on `view.soma and view.tree`, and `view.neuron3d` on `view.tree3d, view.soma3d`.

Each of these then call plot_style, which then calls save_plot, which means that save_plot is called several times per view.neuron if output_path exists.

Since the view.* functions are all `Developer API`, I think it's best if:
1. it's up to the user to call `save_plot`
2. it's up to the user to call `plot_style`
3. `neurom.viewer` handles `save_plot` and `plot_style` to keep the public API the same.

This way, a develop has control over when the plot is styled (if it's necessary to use plot_style), and when it's saved, without repeated calls.  

This would also include whether a plot is shown, so we wouldn't have to use the AGG backend.

**Comment by mgeplf** [comment]
@lidakanari I think you wrote most of the view functionality originally, does the above make sense to you?

**Comment by lidakanari** [comment]
@mgeplf I have no idea about the AGG properties (those controls were all Juan) but I agree about the rest. Do you think we could separate the save - plot style functionality and call the basic plotting options (labels, scaling etc)? If we don't the default matplotlib options will replace current functionality that had been optimized for figures that go into papers - reports etc. About the saving I am completely agree with your suggestion!

**Comment by mgeplf** [comment]
If I'm understanding you correctly, yes, the plot_style stuff will stay, it just won't be called automatically (as long as I can figure out a way to make the spacing stuff work).  The proposed change would mean that developer would write:
```
fig, ax = view.neuron(....)
view.plot_style(ax, ...)
view.save_plot(fig)
```
If they want the optimized figures that you speak of.

Alternatively, they would could use the 'official' api `neurom.viewer(....)` if they want everything in a single call.

Does that work for you?

**Comment by lidakanari** [comment]
Sorry for the misunderstanding. Yes, the decoupling part was clear in your description. Here's an example of an issue that might occur:

I want to create a figure of a neuron. The default behavior (matplotlib) will result in a figure that is scaled according to the last tree you've plotted, which is arbitrary. To resolve this I control the limits of the plot by calling plot_style inside the plotting function. My proposal is to keep this functionality because it is fundamental for the viewer. If you think that calling the plot_style within the viewer is too much, we can call only the plot_limits or whichever function is _really_ needed. Does this sound plausible?

**Comment by mgeplf** [comment]
I'm not sure I follow.  `plot_style` is usually the last function that is called in, say, the `neuron` function.  By moving it outside of that function, and having the user call it, it's the same call that's being made.

Setting the limits will be a bit challenging, and we may have to use plot_limits to set that inside `neuron`, etc, but I will cross that bridge when I get there.  At the moment, many of the limit settings calls are redundant: for instance they get set as the bounding box for each neurite when `neuron` calls `tree`, and then set again at the end, so that the whole neuron is visible.  It would be nice to avoid this, if possible.

**Comment by lidakanari** [comment]
I certainly agree with you that there are redundant calls and it would be great if you can fix this. 

The problem is that some arguments (xlim, ylim) are computed inside the function (and that is not just a trivial function call). If you to call the plot_style inside and outside the function (for example try this to view.neuron) the results are different because the important controls (limits) are modified inside the function. In any case, this is just a warning of what might break, because it took me a few weeks to optimize the output to everyone's convenience. It is up to you so I trust whatever decision you make :)

**Comment by mgeplf** [comment]
done in https://github.com/BlueBrain/NeuroM/pull/608
