### ISSUE TITLE
NeuroM fails to load h5 file

### ISSUE THREAD

**Issue by lidakanari** [BlueBrain/NeuroM#652]
Hi, I tried to load a file from the latest release (unraveled) and it fails to load. I checked a few others files and I get the same error. Could someone fix this? See attachment for file example that fails. 

[vd110315_idE.h5.zip](https://github.com/BlueBrain/NeuroM/files/1337001/vd110315_idE.h5.zip)

**Comment by mgeplf** [comment]
From the file you posted, it seems that the hdf5 you have is organized into 'structure/unraveled' and 'unraveled', but there is a special case here:
https://github.com/BlueBrain/NeuroM/blob/master/neurom/io/hdf5.py#L142

That claims that if the type is unraveled, the name should be 'structure/unraveled'.  So that is weird.

For a quick fix, just changing that line to:
```
groups_stage = stage
```
should allow you to continue.  I'll submit a patch when I get a chance.

**Comment by lidakanari** [comment]
Great! Thanks a lot for looking into this so quickly! 

Yes, that will do for the moment; I will fix this locally.

**Comment by wizmer** [comment]
@mgeplf Do we consider this file to be bugged or should we fix the code ?

**Comment by mgeplf** [comment]
This is an internal format (that is slowly going away), so it's not the most important thing.  On the other hand it's probably only a 2 line fix.  I say we leave it open for now, and find some time for it later.

**Comment by asanin-epfl** [comment]
HDF5v2 is no longer supported, closing.
