### ISSUE TITLE
tree_type_checker(*NEURITES) does not filter out soma

### ISSUE THREAD

**Issue by wizmer** [BlueBrain/NeuroM#804]
since NEURITES is a tuple that includes NeuriteType.all, it will never filter anything out.

Here is a modified version of the existing unit test to test for soma filtration.
```python
def test_tree_type_checker():
    tree_filter = tree_type_checker(NeuriteType.all)
    nt.ok_(tree_filter('fake_tree'))

    mock_tree = Mock()
    mock_tree.type = NeuriteType.axon

    tree_filter = tree_type_checker(*NEURITES)
    nt.ok_(tree_filter(mock_tree))

    mock_tree.type = NeuriteType.soma
    nt.ok_(not tree_filter(mock_tree))  # <- This assertion fails
```

**Comment by asanin-epfl** [comment]
This is a topic for discussion rather. NeuroM followed the logic of NEURON simulation, and considered soma as section hence `NEURITES` were defined right in that paradigm. Now, since NeuroM moved to MorphIO, soma is not considered as section. Hence `.all` can't be part of `NEURITES`. I can drop it from there but I need confirmation from other interesting parties.

@arnaudon can you on behalf of scientists discuss the drop of `NeuriteType.all` from `NEURITES` in `neurom.core.types` module?

**Comment by arnaudon** [comment]
I sent it around to discuss, I'll come back to you. I never use .all myself, but I've seen it in a few places. It may break some codes if we remove it.

**Comment by wvangeit** [comment]
I guess it's a bit of semantic issue. I wouldn't consider the soma as a neurite. But that doesn't mean it's not a section though. 
So maybe the naming NEURITES was a bit unfortunate?

**Comment by asanin-epfl** [comment]
> But that doesn't mean it's not a section though.

@wvangeit  In NeuroM v2 soma is not considered as section because of MorphIO.

**Comment by lidakanari** [comment]
I agree that soma does not make sense as a neurite. However, we need to compute measurements, such as total length, for *all* neurites (including for example axon + dendrites). In addition, a lot of publications require the features for axons + dendrites.

**Comment by asanin-epfl** [comment]
Removing of `.all` won't affect axon + dendrites. They stay. Only soma will be out of measurements. Currently when you use `NEURITES`, you get soma into your measurements as well.

**Comment by lidakanari** [comment]
Thanks @asanin-epfl sorry I did not understand well the proposal. So how can you get axon + dendrites (total) after `all` is removed? Will there be an option for `all` neurites instead? I agree with that, soma should indeed not be considered a neurite.

**Comment by asanin-epfl** [comment]
I propose to change:

```python
NEURITES = (NeuriteType.all,
            NeuriteType.axon,
            NeuriteType.apical_dendrite,
            NeuriteType.basal_dendrite)
```
to
```python
NEURITES = (
            NeuriteType.axon,
            NeuriteType.apical_dendrite,
            NeuriteType.basal_dendrite)
```

> So how can you get axon + dendrites (total) after all is removed?

As you can see from the above `NEURITES` will still give you "axon + dendrites". Unless you have dendrites that use custom types.

> Will there be an option for all neurites instead?

`NeuriteType.all` will still be accessible, and possible to use.

From my point of view there is a serious flaw in calculations with the current `NEURITES` because `NeuriteType.all` allows for any type (soma included). A user calculates a total length of neurites with `NEURITES`, and actually gets soma length included in this calculation.
