### ISSUE TITLE
NeuroM 3.0

### ISSUE THREAD

**Issue by asanin-epfl** [BlueBrain/NeuroM#918]
NeuroM seriously confuses concepts of Neuron and Morphology. Everything that currently has a name `neuron` or `Neuron` must be changed to `morphology` and `Morphology`. This way NeuroM can be clearly used for any topological entity like: Neuron, Glial cell, Vasculature cell, etc.

I suggest a huge renaming of `neuron` to `morphology` and release NeuroM 3.0 with this change.

**Comment by eleftherioszisis** [comment]
Although it is a good idea to generalize the morphological entity, we need to keep in mind that each family of cells may have their own unique features that depend on extra datasets (e.g. perimeters in astrocytes). 

As far as the vasculature is concerned, I believe it is out of the scope of this package because it is a cyclic graph without a specific root, therefore it is quite different and its features may required specialized mechanics.

**Comment by asanin-epfl** [comment]
Thank you so much for feedback @eleftherioszisis.

Unique features are not the problem. NeuroM still can have subclasses for Neuron, Astrocyte, etc. The head of these classes will be `Morphology`.

- Is the name `Morphology` ok for you? What other alternatives can you suggest?

- If NeuroM at some point decides to generalize also vasculature entities, what name can you suggest for such general entity instead of `Morphology`? `Graph`? `Topology`?

**Comment by eleftherioszisis** [comment]
`Morphology` is a good generic name for any sort of entity that can be represented as cross-sections (points + diameters) linked together by segments. Therefore, neurons, glia, spines, and vasculature are all morphologies.

IMHO `Graph` does not imply an embedding in the euclidean space. A social network for instance can be a graph, but it does not fit the criteria for being a Morphology.

**Comment by asanin-epfl** [comment]
Thank you for clarifying.

**Comment by arnaudon** [comment]
This is going to break again several tools ;) But +1 for being consistent in naming these.
