### ISSUE TITLE
Possibly wrong behavior of `trunk_origin_radii` feature

### ISSUE THREAD

**Issue by eleftherioszisis** [BlueBrain/NeuroM#985]
Concerning the `trunk_origin_radii` feature:

https://github.com/BlueBrain/NeuroM/blob/e31eb63b522a3558233d821fcfbb178e6754aa56/neurom/features/morphology.py#L348-L388

It starts from the root and calculates the path-distances of the points as they are laid out from `neurite.points`. However, path distance is defined as the shortest path to the root. Calculating it as the cumulative sum of the segment lengths of the neurite points results in the path length of how the sections are stored. So if from the root we have a fork the left side of which is a tiny tree, the path distances (as they are calculated now) on the right side will carry the total length of the left side.

The path distances need to be calculated so that the shortest path is followed from the node to the root.

See for instance how the section path distance is calculated:
https://github.com/BlueBrain/NeuroM/blob/e31eb63b522a3558233d821fcfbb178e6754aa56/neurom/features/neurite.py#L169-L176

Thoughts?
@lidakanari @arnaudon @adrien-berchet

**Comment by arnaudon** [comment]
Yes, doesn't seem right. I never used that feature (hopefully!), and do it myself when I compute such things, so I know what I'm doing ;)

**Comment by adrien-berchet** [comment]
Ups, that's my bad... :disappointed: 
Indeed I did not consider the case with a branching point in the given distance :facepalm: (in my mind this feature was just to take the mean of a few points close to the root)
We should indeed fix this but what should we do when we have a branching point? Because taking the mean of the diameters of the branches will lead to bad results. Maybe we should only consider the points in the first section?

**Comment by arnaudon** [comment]
Ah ok, what was the original motivation for this feature?

**Comment by arnaudon** [comment]
This was added here: https://github.com/BlueBrain/NeuroM/pull/965 but as you said, there is not best choice for which branch to follow. There may be a best choice if one cares about apical trunk diameter for example, but this will be too specific. Maybe just add a warning if a bif is encountered, so the user knows that the result may be a little weird. Or maybe a flag that if True, will stop the computation at first bif, instead of given path lenght.

**Comment by adrien-berchet** [comment]
> Ah ok, what was the original motivation for this feature?

If I remember it was because sometimes the radii are not reliable near the origin, so with this feature we can take the mean radius of a few points near the origin. So I think it makes sense to use only the first section and ignore the points after the bifurcation. And we can raise a warning if the min value is greater than the path distance of the last point and return the radius on this last point for example.

**Comment by arnaudon** [comment]
Ah yes, when we were trying to correlate trunk angle with trunk radius, or something? It is not a very well-known feature, so I'd say leave it as it is, or add a warning as you said if you prefer.

**Comment by adrien-berchet** [comment]
> Ah yes, when we were trying to correlate trunk angle with trunk radius, or something?

Yeah that's it.

> It is not a very well-known feature, so I'd say leave it as it is, or add a warning as you said if you prefer.

I added a warning and only consider the first section in #986 .

**Comment by arnaudon** [comment]
lovely!
